Ilykov
MrVonny/SaluteStocks pull request #3
Opened 2022-03-08 17:04 UTC by nfrmtk

2022-03-22 15:09 UTC, nfrmtk commented
asd

2022-03-25 21:44 UTC, MrVonny requested changes

2022-03-25 21:44 UTC, MrVonny commented on SaluteStocksAPI/Models/Extensions/Common/CompanyOverviewExtensionFunctions.cs
> +        var lastReport = x.BalanceSheet.AnnualReports.Where(y => y.FiscalDateEnding == currentYear).ToList()[0];
.Where(y => y.FiscalDateEnding == currentYear).ToList()[0] заменить на .Single(y => y.FiscalDateEnding == currentYear)

2022-03-25 21:44 UTC, MrVonny commented on SaluteStocksAPI/Models/Extensions/CompanyOverviewExtension.cs
> +        return rangedValue.HasValue ? queryable.Where(x =>
queryable.Where(x => x.DeptEquityInRange(rangedValue))

2022-03-25 21:44 UTC, MrVonny commented on SaluteStocksAPI/Models/Extensions/Common/CompanyOverviewExtensionFunctions.cs
> +public static class CompanyOverviewExtensionFunctions
Удалить этот класс, добавить readonly свойства в CompanyOverview

2022-03-25 21:44 UTC, MrVonny commented on SaluteStocksAPI/Models/Extensions/CompanyOverviewExtension.cs
>  public static class CompanyOverviewExtension
`public static partial`

2022-03-25 21:44 UTC, MrVonny commented on SaluteStocksAPI/Models/Extensions/CompanyOverviewExtension.cs
> +        return rangedValue.HasValue ? queryable.Where(x => x.IncomeStatement.GrowthRevenue5Years.HasValue&&
Принцип DRY нарушен. 
Сдлеать T  в RangedValue<T> реализующим интерфейс IComparable. И добваить метод IsInRange(T value);

2022-03-25 21:44 UTC, MrVonny commented on SaluteStocksAPI/Models/FundamentalData/CompanyOverview.cs
> +            return sorted[0].TotalRevenue.Value - sorted[X].TotalRevenue.Value;
Минус? Рост считается в процентах

2022-03-25 21:44 UTC, MrVonny commented on SaluteStocksAPI/Models/FundamentalData/CompanyOverview.cs
> +    public decimal? EPSGrowthXYears(short X)
Параметры функции пишутся с маленькой буквы)

2022-03-25 21:44 UTC, MrVonny commented on TestProject1/UnitTest1.cs
> +        var screenerService = new ScreenerService(new StocksContext(new DbContextOptions<StocksContext>()));
И как, работает?)

2022-03-25 21:44 UTC, MrVonny commented on SaluteStocksAPI/Service/ScreenerService.cs
>              //ToDo: Uncomment when implemented
Убрать ToDO

2022-03-25 21:44 UTC, MrVonny commented on SaluteStocksAPI/Models/FundamentalData/CompanyOverview.cs
> +        return earnings[0].ReportedEPS.Value - earnings[X].ReportedEPS.Value;
Минус? Рост считается в процентах

2022-03-25 21:44 UTC, MrVonny commented on SaluteStocksAPI/Models/FundamentalData/IncomeStatement.cs
> +    public decimal? GrowthRevenue1Year { get
У нас уже есть такая проперти в CompanyOverview. Дубликат кода.

2022-03-26 11:49 UTC, merged